Fix for Average calculation problems since #589
poblabs/weewx-belchertown pull request #619
Opened 2021-03-03 14:28 UTC by michaelundwd

This fixes the problem with the display of average values since #589.  The remedy was to change the avg calculation to sum/count, not wsum/count as originally proposed.  I have made the changes for both sqlite and mysql, having checked that it works correctly for sqlite.

2021-03-03 14:43 UTC, ArendPWS requested changes
Can you try this first, this is the way WeeWX seems to calculate the (weighted) averages

ROUND(SUM(wsum)/ SUM(sumtime),2) as obs ' \

2021-03-03 15:40 UTC, michaelundwd commented
Thanks for this.  I am happy to change to the weighted average.  I have tried with my data, and it yields the same result, presumably because my archive interval is the same throughout?  I used sum/count as the avg used in version 1.2 is just that - sqlite has no concept of a weighted average.  My main concern was reducing the the size of the average by a factor of 300...

However, this only applies to where the aggregate_interval is 86400.  For all other examples, the code uses avg which is an unweighted average.  Is this significant? All my charts use an aggregate_interval of 86400.

2021-03-03 15:54 UTC, ArendPWS commented
WeeWX uses it (SUM(wsum)/ SUM(sumtime)) for both MySQL and sqlite, so if it works we should stick to that. Weighted averages are especially significant for average temperatures in meteorology.

2021-03-03 16:01 UTC, michaelundwd commented
Agreed we should follow weewx for consistency.  However, the changes we are discussing are in belchertown.py that access sqlite and mysql directly as I see it, and these changes will only apply where the aggregate_interval is 86400.  Is it worth worrying about any others?

2021-03-03 17:18 UTC, ArendPWS commented
No, the weighted average only applies to archive_day (like WeeWX).

2021-03-03 17:55 UTC, michaelundwd commented
New commit https://github.com/poblabs/weewx-belchertown/pull/619/commits/e99b0df24b6d99421983b9e3b018cabad1984623 using weighted average following advice from @ArendPWS, for which many thanks.
Michael

2021-03-04 08:57 UTC, norecords commented
That works for me, thanks @michaelundwd and @ArendPWS

2021-03-07 14:26 UTC, ArendPWS commented
Some general thoughts about quering the databases directly:

1. This will ofcourse only work for observations stored in the database
2. XTypes that are not stored in the database can not be retreived with the code that starts from:

        if xAxis_groupby or len(xAxis_categories) >= 1:

3. Perhaps this kind of optimizations should be part of WeeWX and not Belchertown

2021-03-07 16:49 UTC, michaelundwd commented
@ArendPWS I understand your final point, but it's not clear to me how many of the graph queries use direct access to the database and those that rely on weewx.  Can you help me by pointing out any code in belchertown.py that uses weewx please?

2021-03-07 17:35 UTC, ArendPWS commented
@michaelundwd

I was just thinking about possible issues with observations not stored in the database (e.g. some XTypes). At the moment I have the idea that not to many users are applying these. But perhaps it will become an issue of more relevance in the future. I will get back to this at some point when I have more time at my disposal.

For now your latest changes to the PR are just fine and can be safely merged by @poblabs. 👍

2021-03-07 17:46 UTC, michaelundwd commented
@ArendPWS 
Thanks - look forward to the discussion at a later stage.  Maybe I will have found my way around belchertown.py by then!

2021-03-09 14:41 UTC, merged